old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        # use 'old_sound_rabbit_mq.task_producer' service to send data.
        minecraft:
            connection: default
            exchange_options: { name: 'minecraft', type: direct, durable: false }
            default_routing_key: 'bot-input'
            service_alias: minecraft
