security:
    enable_authenticator_manager: true
    providers:
        mongo_provider:
            mongodb:
                class: App\Document\User
                property: id
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: mongo_provider
            custom_authenticators:
                - App\Security\DiscordAuthenticator
            logout:
                path: logout

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
